site_name: Multi-Step Transcriber
site_url: https://github.com/geraldthewes/multistep-transcriber # Replace if you have a deployed docs site URL
repo_url: https://github.com/geraldthewes/multistep-transcriber
repo_name: geraldthewes/multistep-transcriber
edit_uri: "" # Optional: link to edit page, e.g., edit/main/docs/
docs_dir: documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Algorithm: Planning.md
  - API Reference:
    - 'mst Package': api/mst.md
    - 'VideoTranscriber': api/video_transcriber.md
 #   - 'Core Steps':
 #     - 'Caching': api/steps/caching.md
 #     - 'Diarization': api/steps/diarization.md
 #     - 'Entities': api/steps/entities.md
 #     - 'Formatting': api/steps/format.md
 #     - 'Helpers': api/steps/helpers.md
 #     - 'Introductions': api/steps/introductions.md
 #     - 'Merge Sentences': api/steps/merge_sentences.md
 #     - 'Models': api/steps/models.md
 #     - 'Standardize': api/steps/standardize.md
 #     - 'Topic Segmentation': api/steps/topic_segmentation.md
 #     - 'Transcription': api/steps/transcription.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google # Matches the style used in VideoTranscriber
            show_root_heading: true # Use the heading from the identifier itself
            show_source: true       # Show/hide source code blocks
            members_order: source   # Order of members as in source code
            separate_signature: true # Render signature separately from docstring
            merge_init_into_class: true # Merge __init__ docstring into class docstring
            # show_signature_annotations: true # Show type hints in signatures
            # show_if_no_docstring: true # Show members even if they have no docstring
            # heading_level: 2 # Default heading level for mkdocstrings content
          import:
            - url: https://docs.python.org/3/objects.inv
            # If you use Pydantic or other libraries with intersphinx inventories, add them here:
            # - url: https://pydantic-docs.helpmanual.io/objects.inv

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geraldthewes/multistep-transcriber

copyright: Copyright &copy; 2024 Gerald Thewes # Update with your name/organization
